"""ammonix_core: the Ammonix data contract, schema v0.1 plus the v0.2 deltas.

Every entity the pipeline reads or writes, as Pydantic models. The contract
follows docs/ammonix_schema_v0.1.md with the amendments declared in
docs/mlb_benchmark_spec_v0.2.md Section 9 (game-level fold grouping,
DatasetDescriptor corpus_version/date_range, CoverageReport.dropped with the
reserved ActionId 'drop', TestReport trap verdicts).
"""

from ammonix_core.loops import LoopIteration, LoopRun, LoopSpec
from ammonix_core.schema import (
    DROP_ACTION_ID,
    ActionMap,
    ActionMapRule,
    ActionObject,
    AmmonixConfig,
    Attribution,
    BasisManifest,
    Calibrator,
    CanonicalAction,
    CheckResult,
    ClassifierSpec,
    ContextSource,
    CoverageReport,
    DatasetDescriptor,
    DecisionQuestion,
    DeterminismPin,
    EscalationRecord,
    Example,
    ExecutionTrace,
    ExpectedResultSpec,
    FeatureSpec,
    FoldMetrics,
    FoldPlan,
    HarnessArtefacts,
    HistorySpec,
    IterationRecord,
    LabelPolicy,
    LiveCase,
    LLMPin,
    Neighbour,
    Outcome,
    PromptTemplate,
    QPsiRecord,
    QuarantineManifest,
    RawData,
    RawState,
    RecommendationPolicy,
    RegionModelSpec,
    RetrievalResult,
    Scope,
    Skill,
    SplitPolicy,
    SwarmConfig,
    TestReport,
    Tokenizer,
    TrainedFoldModel,
    Tribe,
    TribeStats,
    UniverseIndex,
    UniverseRecord,
)

__all__ = [
    "ActionMap",
    "ActionMapRule",
    "ActionObject",
    "AmmonixConfig",
    "Attribution",
    "BasisManifest",
    "Calibrator",
    "CanonicalAction",
    "CheckResult",
    "ClassifierSpec",
    "ContextSource",
    "CoverageReport",
    "DatasetDescriptor",
    "DecisionQuestion",
    "DeterminismPin",
    "DROP_ACTION_ID",
    "EscalationRecord",
    "Example",
    "ExecutionTrace",
    "ExpectedResultSpec",
    "FeatureSpec",
    "FoldMetrics",
    "FoldPlan",
    "HarnessArtefacts",
    "HistorySpec",
    "IterationRecord",
    "LabelPolicy",
    "LiveCase",
    "LLMPin",
    "LoopIteration",
    "LoopRun",
    "LoopSpec",
    "Neighbour",
    "Outcome",
    "PromptTemplate",
    "QPsiRecord",
    "QuarantineManifest",
    "RawData",
    "RawState",
    "RecommendationPolicy",
    "RegionModelSpec",
    "RetrievalResult",
    "Scope",
    "Skill",
    "SplitPolicy",
    "SwarmConfig",
    "TestReport",
    "Tokenizer",
    "TrainedFoldModel",
    "Tribe",
    "TribeStats",
    "UniverseIndex",
    "UniverseRecord",
]
